apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
  labels:
    app: orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics.portNumber: "3000"
        k8s.grafana.com/metrics.path: "/metrics"
        k8s.grafana.com/job: "api-b"
    spec:
      serviceAccountName: orchestrator-ksa
      containers:
        - name: orchestrator
          image: us-central1-docker.pkg.dev/motorcycle-workshop-v2/orchestrator-images/orchestrator:v1.1.0
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: orchestrator-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"